"""
models/application_package.py
Output model for a generated application package per scheme.
Matches architecture.md §4.5.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class ApplicationPackage(BaseModel):
    """
    The complete output for one unclaimed scheme:
    - A plain-language summary in the citizen's chosen language
    - A document checklist
    - A reference to the generated pre-filled PDF
    """

    scheme_id: str
    scheme_name: str
    summary_text: str = Field(
        ...,
        description=(
            "3-5 line plain-language summary in the citizen's language. "
            "Generated by Gemini per the summary_generation_prompt."
        ),
    )
    checklist: List[str] = Field(
        default_factory=list,
        description="Ordered list of required documents the citizen must gather",
    )
    pdf_file_ref: Optional[str] = Field(
        default=None,
        description=(
            "Cloud Storage URI (gs://) or signed HTTPS URL of the generated PDF. "
            "None if PDF generation is still pending."
        ),
    )
    # Always included; no exceptions per architecture.md §8
    disclaimer: str = Field(
        default=(
            "This is a draft based on self-declared information and publicly available "
            "scheme rules. Please verify details with the issuing department before submission."
        )
    )


class MatchedScheme(BaseModel):
    """Intermediate model — scheme matched by rules engine, not yet claim-status checked."""

    scheme_id: str
    scheme_name: str
    category: str
    matched_conditions: List[str] = Field(
        default_factory=list,
        description="Human-readable list of conditions that matched (for explainability)",
    )


class UnclaimedScheme(MatchedScheme):
    """A matched scheme confirmed as not already being claimed by the citizen."""

    claim_status: str = Field(
        default="unclaimed",
        description="'unclaimed' | 'unknown' (self-declaration or ledger result)",
    )
